# Generated by Django 3.2.5 on 2021-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210806_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fullBlogLink',
            field=models.TextField(),
        ),
    ]
