# Generated by Django 3.2.4 on 2021-08-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210807_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='video',
        ),
    ]
