# Generated by Django 3.2.4 on 2021-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(upload_to='media/portfolio/videos'),
        ),
    ]
