# Generated by Django 3.2.4 on 2021-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
